---
title: "NSF GRFP personal statement example"
summary: "My successful NSF GRFP personal statement with advice."
author: Jane Pascar
date: 2019-12-17
categories: []
tags: []
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(collapse = TRUE)
```
There is a lot of information, advice, and tips already available about the [National Science Foundation (NSF)](https://www.nsf.gov/) [Graduate Research Fellowship Program (GRFP)](https://www.nsfgrfp.org/) but I want to post my 2018 personal statement as an example: 

##### [Pascar_2018_GRFP_Personal_Statement.pdf](../2018_personal_GRFP.pdf)  

It is important to remember that unlike some other fellowships and scholarships, the NSF GRFP places a great deal of emphasis on **funding the scientist and not just the scientific proposal**.  

I began roughly outlining my personal statement about 2 months prior to the due date and worked simultaneously on the research proposal. I found this useful because if I hit writers block or a bump in the road collecting preliminary data it was nice to be able to switch to the personal statement to remain productive.  

It was also nice to be able to send a semi-complete version of my personal statement to my letter writers so they could 1. see what I was emphasizing about my experiences with them and 2. see what I had been up to since I left their labs and where I envision my grad program going. 

In addition to receiving feedback on my personal statement from my advisors, I attended workshops held by Syracuse University's [Center for Fellowship and Scholarship Advising Center](https://nationalscholarships.syr.edu/). In these workshops, other undergrads and grad students applying had the opportunity to receive feedback from each other and professional staff. After these workshops I met two more times with the director of the CFSA to help review my statement for any last-minute edits. If your school doesn't have an office dedicated solely to scholarship advising check out the writing center for advice.  

Overall, I found participating in workshops super helpful! In hindsight, my initial draft before receiving feedback was so boring. I basically turned my CV into paragraphs. Even though I find it difficult to write about myself, meeting with the CFSA helped me to articulate why I am so excited about science and helped me explain how I got where I am and where I see myself going.  

###### Remember: tell a story about yourself!
  
*****  
Here are resources complied by others I used while preparing my application (they also link to more resources):  
- [Alex Wang's Website](https://www.alexhunterlang.com/nsf-fellowship)  
- [Yaniv Brandvain's GitHub Repo](https://github.com/ybrandvain/GRFP)  

Additionally...  
- Twitter: [#GRFP](https://twitter.com/search?q=%23grfp&src=typed_query) and [#NSFGRFP](https://twitter.com/search?q=%23nsfgrfp&src=typed_query)  
- Reddit: [r/GradSchool](https://www.reddit.com/r/GradSchool/), [r/gradadmissions](https://www.reddit.com/r/gradadmissions/), and [r/AskAcademia](https://www.reddit.com/r/AskAcademia/)  
- ~~GradCafe~~: Avoid the GradCafe forum. During my first GRFP application cycle before I started grad school, I would check it occasionally and it made me really stressed and anxious and there really isn't even advice! There are a lot of people posting their accolades which inevitably caused imposter syndrome to set in. Furthermore, after the application due date passes, the forum mostly consists of speculating when the results will be posted.  

My advice is:  
1. Upon submittal, celebrate the victory of completing a fellowship application.  
2. Do not read over your application again (you will likely find a spelling, grammatical, or formatting error... I did and it haunted me for months, but, realistically no one will probably even notice.)   
3. Try to put it in the back of your mind until April and the announcement is actually made.