---
title: "Starting the switch to LaTeX"
summary: "Fed up with Microsoft Word, I'm finally commiting to learning LaTeX."
author: Jane Pascar
date: 2020-01-10
categories: []
tags: []
draft: true
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(collapse = TRUE)
```

Writing your dissertation is already difficult, why make it more difficult by trying to format such a huge document in Microsoft Word? I have heard so many people spend ~~hours~~ *days* trying to format their dissertation work!  

I still have quite a few years before I am at this step but I already know that formatting is going to be pretty low on my priorities, I would rather focus on the science! I've heard really good things about LaTeX.  

None of my collegues that I know of use LaTeX so I envision I will only use it on papers where I am the sole author but my distain for Word formatting seems like a fair trade. 

This article clearly lists the advantages: [The Only LaTeX Editor Guide You Will Need In 2019](https://blog.typeset.io/the-only-latex-editor-guide-youll-need-in-2018-e63868fae027)  

### Learning by example.  
Many beginner guides to LaTeX I came across referenced the [LaTeX Wikibook](https://en.wikibooks.org/wiki/LaTeX). I glanced through some of the pages, but honestly it contains so much information I was overwhelmed and eager to just start making documents. So, yes the [LaTeX Wikibook](https://en.wikibooks.org/wiki/LaTeX) is a very good source of information but it is definitely not required reading before getting started, *especially* if you already have a foundation in a coding language.  

Feeling confident, I decided to convert my CV to LaTeX from Microsoft Word. I have spent an embarasingly large amount of time formatting my CV in word and I still don't even really like it. Here is my [old CV](../word_CV.pdf) that I've marked up with some of my gripes. To be fair some (most?) of these complaints are my fault but also Word makes it very difficult sometimes to do a simple task. 

I browsed GitHub for some examples of CVs to pick out a design I liked that included all of the necessary source code.  

Shoutout to [Byungjin Park](https://www.posquit0.com/), their repo [Awesome-CV](https://github.com/posquit0/Awesome-CV) has almost 10k stars and is pretty active through commits and pull requests. It is also just a really nicely designed CV.  

However, I ended up choosing [Geoff Boeing's](https://geoffboeing.com/) [academic CV](https://github.com/gboeing/cv) design.  

I made a free Overleaf account and uploaded the .tex file from Geoff's Github repo.  

From there it was mostly just trial and error. Overleaf automatically compiled the .tex file so I could read through Geoff's code and see how it translated to the PDF. Overleaf also has this really cool feature where if you double-click text in the PDF, the source code console will jump to where that part of the code is.  

I didn't change any of the formatting code like font family, alignment, font size, etc. But I did read through this part of the code until I more or less understood what was going on. 

I essentially then just switched all of Geoff's information with mine. He had a lot more sections that I needed so I would delete or comment out those parts of code. I rearranged the order of some sections and based on the already written code I made my own sections for outreach and mentoring service. I also rearranged some of his sections. For example, under Education I preferred to list the years of my degrees rather than their titles.  

The most difficult part was making certain words bold or italicized. I'm still not exactly sure what the difference between \\textit, \\textbf, \\it, \\bf, or \\emph is and I know I used them interchangably throughout my document ¯\\_(ツ)_/¯ but it at least looks the way I intended. 

### The final product.
Here is my [LaTeX CV](../pascar_cv.pdf)! I probably spent a few hours just messing around in Overleaf 